#!/usr/bin/env sh
set -eu

repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
codex_home=${CODEX_HOME:-"$HOME/.codex"}
rules_dir="$codex_home/rules"
dest="$rules_dir/codexrc.rules"
backup_dir="$codex_home/backups/$(date +%Y%m%d-%H%M%S)"

vim_check_modified="$repo_dir/bin/vim-check-modified"
vim_checktime="$repo_dir/bin/vim-checktime"

tmp=${TMPDIR:-/tmp}/codexrc.rules.$$
trap 'rm -f "$tmp"' EXIT HUP INT TERM

cat >"$tmp" <<EOF
# Generated by $repo_dir/install-rules.sh.
# Re-run that script after moving this repository.
prefix_rule(
    pattern = ["$vim_check_modified"],
    decision = "allow",
    justification = "Allow local Vim buffer safety check before edits",
    match = [
        "$vim_check_modified AGENTS.md",
    ],
)

prefix_rule(
    pattern = ["$vim_checktime"],
    decision = "allow",
    justification = "Allow local Vim refresh after external edits",
    match = [
        "$vim_checktime",
    ],
)
EOF

mkdir -p "$rules_dir"

if [ -e "$dest" ] || [ -L "$dest" ]; then
  if cmp -s "$tmp" "$dest"; then
    printf 'ok: %s already up to date\n' "$dest"
    exit 0
  fi

  mkdir -p "$backup_dir"
  mv "$dest" "$backup_dir/"
  printf 'backup: %s -> %s/\n' "$dest" "$backup_dir"
fi

mv "$tmp" "$dest"
trap - EXIT HUP INT TERM
printf 'write: %s\n' "$dest"
printf 'done: restart Codex for rules changes to take effect\n'
